export const tweets = [
	'se ganharmos digo easy',
	'só dão dodge quando me calha xerath',
	'convida a neeyd',
	'não vou po bot com o random',
	'não jogo solocu',
	'tiessême XDXD',
	'vou jogar de mota',
	'focus support noob',
	'até ficas paneleiro dos olhos com a minha vayne',
	'íamos era csgo',
	'dá ulti para iniciar',
	'só faltam 20 min para dar surrender',
	'kda > ser giro',
	'lag',
	'o rato parou',
	'como é que ele já tem ulti outra vez',
	'*morre gankado* "jungler no flash"',
	'temos sempre os piores bonecos no aram. vou fazer um excel para comparar',
	'BAZOU TUDO',
	'como é que isto me acertou',
	'não posso, vou jantar daqui a um bocado',
	'TWICE DA BOUNTY',
	'perder contra o mota',
	'este thresh tá me a foder e eu a ver',
	'lolypoppy fds que rico',
	'report junglerino',
	'viktor é memo fixe a support',
	'fds deixem-me dar lifesteal',
	'*está 2-12-2* é que eu até tou a jogar bem',
	'não consigo dar ultimate, tá bugado',
	'e acertou-me a merda da seta',
	'esta riot só tem merda na cabeça, só pode',
	'eheh tostadeira eheh jogar no gameboy eheh',
	'joguem este sem mim, vou lavar os dentes',
	'perem aí que vou cagar',
	'tá calculating differences, vou buscar a casio XDDX',
	'convida o relis',
	'só apanho meninos especiais na jungle',
	'quando tamos a ganhar só sai cloud drakes',
	'já mudaram o rift herald outra vez?',
	'TIESSEEEME'
];


export default {
	tweets
};
