module.exports = {
	text : [
		'se ganharmos digo easy',
		'só dão dodge quando me calha xerath',
		'siga aram',
		'convida a neeyd',
		'não vou po bot com o random',
		'não jogo solocu',
		'tiessême',
		'vou jogar de mota',
		'focus support noob',
		'até ficas paneleiro dos olhos com a minha vayne',
		'íamos era csgo',
		'dá ulti para iniciar',
		'só faltam 20 min para dar surrender',
		'kda > ser giro',
		'lag',
		'o rato parou',
		'como é que ele já tem ulti outra vez',
		'*morre gankado* "jungler no flash"',
		'temos sempre os piores bonecos no aram. vou fazer um excel para comparar',
		'BAZOU TUDO',
		'como é que isto me acertou',
		'não posso, vou jantar daqui a um bocado',
		'TWICE DA BOUNTY',
	]
}